paths : 
    
    #jquery : 'jquery',
    #underscore : 'underscore',
    #backbone : 'backbone',
    
    text : require-text
    
    collections : 'backbone/collections'
    models : 'backbone/models'
    views : 'backbone/views'
    templates : 'backbone/templates'
    controllers : 'backbone/controllers'
    
  
 #shim : 
   # bootstrap : 
     # deps : [ 'jquery' ],
     # exports : 'Bootstrap'
    